Add AmneziaWG protocol improvements
amnezia-vpn/amneziawg-linux-kernel-module pull request #3
Opened 2024-03-22 12:42 UTC by leninalive

2024-03-22 13:05 UTC, tiaga approved these changes

2024-03-22 13:47 UTC, pokamest requested changes

2024-03-22 13:47 UTC, pokamest commented on src/Kconfig
> +	tristate "IP: WireGuard (Amnezia VPN) secure network tunnel"
"IP: AmneziaWG secure network tunnel"

2024-03-22 13:47 UTC, pokamest commented on src/main.c
> +	pr_info("WireGuard " WIREGUARD_VERSION " (Amnezia VPN) loaded. See www.wireguard.com for information.\n");
AmneziaWG" WIREGUARD_VERSION "loaded

2024-03-22 13:47 UTC, pokamest commented on src/main.c
> +MODULE_DESCRIPTION("WireGuard (Amnezia VPN) secure network tunnel");
AmneziaWG secure network tunnel

2024-03-22 13:47 UTC, pokamest commented on src/patches/000-initial-amneziawg.patch
> ++	pr_info("WireGuard " WIREGUARD_VERSION " (Amnezia VPN) loaded. See www.wireguard.com for information.\n");
AmneziaWG WIREGUARD_VERSION loaded

2024-03-22 13:47 UTC, pokamest commented on src/patches/000-initial-amneziawg.patch
> ++MODULE_DESCRIPTION("WireGuard (Amnezia VPN) secure network tunnel");
AmneziaWG secure network tunnel

2024-03-22 15:14 UTC, pokamest commented on src/main.c
> +	pr_info("WireGuard " WIREGUARD_VERSION " (Amnezia VPN) loaded. See www.wireguard.com for information.\n");
pr_info("AmneziaWG" WIREGUARD_VERSION " loaded. See amnezia.org for information.\n");

2024-03-22 15:29 UTC, tiaga approved these changes

2024-03-22 15:35 UTC, pokamest approved these changes

2024-03-22 15:37 UTC, merged

2024-06-10 09:57 UTC, korzhyc commented
This won't build on multi-core system or without `-j 1` param.
https://github.com/amnezia-vpn/amneziawg-linux-kernel-module/blob/40a9e512f062a7e2868866109d2431c3fd321c4c/src/Makefile#L18-L19